# Generated by Django 5.1.6 on 2025-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image(for accessibility)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL to link the banner to ', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='Date when the banner starts showing', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date when the banner stops showing', null=True)),
            ],
        ),
    ]
